version: '3.8'
services:
  mysql:
    image: mysql:8.4.6
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=qwer123456
      - TZ=Asia/Shanghai
    volumes:
      - ./log:/var/log/mysql
      - ./data:/var/lib/mysql
      - ./conf.d:/etc/mysql/conf.d
    ports:
      - "3306:3306"
    networks:
      - my-net
networks:
  my-net:
    external: true