version: '3.8'
services:
  kibana: 
    image: kibana:8.19.4
    container_name: kibana
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    networks:
      - my-net
networks:
  my-net:
    external: true