server:
  port: 8081
spring:
  application:
    name: product-service
  config:
    import:
      - nacos:${spring.application.name}.yaml?group=product
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8858
    nacos:
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: public
      config:
        server-addr: 127.0.0.1:8848
        group: product
        namespace: public
        file-extension: yaml
