server:
  port: 8080
spring:
  config:
    import:
      - nacos:mysql.yaml?group=order
      - nacos:${spring.application.name}.yaml?group=order
  application:
    name: order-service
  cloud:
#    loadbalancer:
#      nacos:
#        enabled: true
    openfeign:
      httpclient:
        hc5:
          enabled: true
    nacos:
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: public
      config:
        server-addr: 127.0.0.1:8848
        group: order
        namespace: public
        file-extension: yaml