version: '3.8'
services:
  skywalking-oap:
    image: apache/skywalking-oap-server:9.5.0
    container_name: skywalking-oap
    ports:
      - 11800:11800
      - 12800:12800
    networks:
      - my-net
    environment:
      SW_CORE_RECORD_DATA_TTL: 15
      SW_CORE_METRICS_DATA_TTL: 15
      SW_STORAGE: elasticsearch
      SW_STORAGE_ES_CLUSTER_NODES: skywalking-es:9200
      SW_STORAGE_ES_INDEX_REPLICAS_NUMBER: 0
      SW_ENABLE_UPDATE_UI_TEMPLATE: true
      TZ: Asia/Shanghai
      JAVA_OPTS: "-Xms2048m -Xmx2048m"
  skywalking-ui:
    image: apache/skywalking-ui:9.5.0
    container_name: skywalking-ui
    depends_on:
      - skywalking-oap
    networks:
      - my-net
    ports:
      - 8060:8080
    environment:
      SW_OAP_ADDRESS: http://skywalking-oap:12800
networks:
  my-net:
    external: true
